# AWS Aliases
alias av="aws-vault"
alias aws-me="aws-vault exec dave.konopka --duration=8h"

export GEM_HOME="$HOME/.gem"

export PATH="$HOME/.cask/bin:$PATH"
export PATH="$HOME/.gem/bin:$PATH"

export RUBY_CONFIGURE_OPTS="--disable-install-doc --with-openssl-dir=$(brew --prefix openssl@3)"

export GPG_TTY=$(tty)

op-load-secrets() {
  # Skip 1Password in VSCode, Cursor, etc.
  #[[ "$TERM_PROGRAM" =~ "vscode" ]] && return
  export OPENAI_API_KEY=`op item get 'OpenAI CLI Key' --field 'password' --vault 'Employee' --reveal`
  export TENV_GITHUB_TOKEN=`op item get 'TENV Github Token' --field 'password' --vault 'Platform Team' --reveal`
}
#op-load-secrets

# If you want auto install versions
export TENV_AUTO_INSTALL=true
export TG_TF_PATH=terraform

# This gets rid of the Terraform version prefixing
export TG_TF_FORWARD_STDOUT=true
export TERRAGRUNT_LOG_DISABLE=true

export PATH=$(tenv update-path)

pull-claude-mds() {
    local repo="$HOME/Projects/claude/claude-mds"
    [[ -d "$repo/.git" ]] || return 0
    git -C "$repo" pull --ff-only --prune --quiet
}

claude-gt() {
  local dirs=()

  # Always include global
  dirs+=(~/Projects/claude/claude-mds/global)

  # Add discipline/team dirs as needed.
  # Uncomment the ones relevant to you, or add logic to auto-detect.
  dirs+=(~/Projects/claude/claude-mds/disciplines/backend)
  # dirs+=(~/dev/claude/claude-mds/disciplines/mobile)
  # dirs+=(~/dev/claude/claude-mds/teams/ai-leadership)

  local add_dir_args=()
  for d in "${dirs[@]}"; do
    if [[ -d "$d" ]]; then
      add_dir_args+=("$d")
    fi
  done

  if [[ ${#add_dir_args[@]} -gt 0 ]]; then
    CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD=1 command claude --add-dir "${add_dir_args[@]}" "$@"
  else
    command claude "$@"
  fi
}

codex-gt-refresh-agents () {
    local files=(
        "$HOME/.codex/AGENTS.source.md"
        "$HOME/Projects/claude/claude-mds/global/CLAUDE.md"
        "$HOME/Projects/claude/claude-mds/disciplines/backend/CLAUDE.md"
    )

    mkdir -p "$HOME/.codex"

    {
        printf '# AGENTS.md\n\n'
        printf 'Generated by codex-gt-refresh-agents. Do not edit directly.\n\n'

        local f
        for f in "${files[@]}"; do
            if [[ -f "$f" ]]; then
                printf '\n\n---\n\n# Imported from %s\n\n' "$f"
                cat "$f"
            fi
        done
    } > "$HOME/.codex/AGENTS.md"
}

( { pull-claude-mds; codex-gt-refresh-agents; } 2>"$HOME/.codex/gt-refresh.log" & )
