# Prefix key
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Splits
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file "$HOME/.tmux.conf" \; display-message "tmux.conf reloaded"

set-option -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'fabioluciano/tmux-powerkit'
set -g @plugin 'ofirgall/tmux-window-name'
# set -g @plugin 'hiroppy/tmux-agent-sidebar'

# Workaround for claude binary naming
# https://github.com/anthropics/claude-code/issues/49852#issuecomment-4328517818
set -g automatic-rename-format '#{?pane_in_mode,[tmux],#{?#{m:*.*.*,#{pane_current_command}},claude:#{b:pane_current_path},#{pane_current_command}}}#{?pane_dead,[dead],}'

set -g @powerkit_plugins "weather,datetime"
set -g @powerkit_theme "catppuccin"
set -g @powerkit_theme_variant "frappe"
set -g @powerkit_plugin_datetime_format "%b %d %A"
set -g @powerkit_plugin_weather_location "Philadelphia, Pennsylvania"
set -g @powerkit_plugin_weather_units "u"
set -g @powerkit_active_window_title "#W"
set -g @powerkit_inactive_window_title "#W"

# automatically name panes
set-option -g status-interval 5

# move status line to top
set-option -g status-position top

# turn off status bar if only one window
set-option -g status off
set-hook -g after-new-window      'if "[ #{session_windows} -gt 1 ]" "set status on"'
set-hook -g after-kill-pane       'if "[ #{session_windows} -eq 1 ]" "set status off"'
set-hook -g pane-exited           'if "[ #{session_windows} -eq 1 ]" "set status off"'
set-hook -g window-layout-changed 'if "[ #{session_windows} -eq 1 ]" "set status off"'

set-option -g allow-rename off

# Window tab naming
set -g @tmux_window_name_shells "['bash', 'fish', 'sh', 'zsh']"
set -g @tmux_window_dir_programs "['nvim', 'vim', 'git']"
set -g @tmux_window_name_use_tilde "True"
set -g @tmux_window_name_max_name_len "20"

# Get home, end keys working in neovim
bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"

bind-key -T copy-mode-vi Escape send-keys -X cancel
bind-key -T copy-mode-vi C-c send-keys -X cancel

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

set -g mouse on

bind -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X scroll-down

run '~/.tmux/plugins/tpm/tpm'
